### ISSUE TITLE
T5 Meeting 17 - Nov 20, 2023

### ISSUE THREAD

**Issue by katrina799** [wangq131/4G06CapstoneProjectT5#200]
## T5 Meeting 01 Info
- **Date**: 2023/11/20
- **Time**: 16:00 - 17:00
-  **Location**: Virtual, via Teams
- **Attendees**: 

	- [x] @wangq131 (Qianni Wang)
	- [x] @qinj15 (Jingyao Qin)
	- [x] @shis20 (Shuting Shi)
	- [x] @songc12 (Chenwei Song)
	- [x] @gaoq20 (Qiang Gao)

- **Meeting Lead**: @songc120 
- **Scribe**: @gaoq20 

## Agenda

- PoC tomorrow
## Todo
https://github.com/wangq131/4G06CapstoneProjectT5/issues/201

## Meeting notes

- Demonstration Rehearsal, be familiar with the procedure
- Go through https://github.com/wangq131/4G06CapstoneProjectT5/blob/main/docs/PoC/PoC_workflow.md
- make sure csv for mock courses is cleaned
- Everyone is assigned something for POC https://github.com/wangq131/4G06CapstoneProjectT5/issues/201
- Demonstration Rehearsal tonight at 10 pm
