### ISSUE TITLE
9/20 Meeting with supervisor questions checklist

### ISSUE THREAD

**Issue by songc120** [wangq131/4G06CapstoneProjectT5#3]
Meeting with the supervisor at 14:00 on 9/20/2023;

To discuss further steps and ask some questions about the ongoing project

- [ ] Clarify problem statement: problem, input & output, stakeholders, environment, goals, stretch goals.

- [ ] Clarify PoC demo plan: the main risk, what to demo.

- [ ] Clarify dev plan: confirm technology, code standard and project 

- [ ] Project Name & Repo Name

--- Chenwei Song ---

- [x] NDA: Do we need to make this repo private?

- [x] CICD: Are we going to inherit existing project?

- [x]  What are our stakeholders? Will the project only be used by the lab?

--- Qiang Gao ---
- [x] Is there any constraint for a programming language?

- [ ] Skills and Knowledge required?

- [ ] Is there any funding for this project?

--- Qianni Wang ---
- [x] How do we plan our meeting in the following year, and how frequently, and where (virtually or in person)? 

- [x] Is there an existing code repo that contains code related to this project?

- [x] Who will be added to our project board/project repo as the collaborators/supervisors (I should probably do it)?
- [x] What are the goals for our project? Or how can we measure it?
- [x] Why do you think this project is important, or how it is going to impact people's life?
- [x] We have lots documents/assignments that need to be done along the project, do you think you could review them when you have time and provide us some feedback if possible? All of the documents can be found in our github repo and we could add you as collaborator so that you could access it, but how can we and how frequent will we receive your feedback?

---Jingyao Qin ---

- [x] What specific problems or challenges are you hoping this software will address?

- [ ] Do you have other constraints like hardware requirements, operating system capability, and software version requirements you want to let us know?

- [ ] How would you assess the significance of this project for the users?

- [ ] Who are the primary end-users or beneficiaries of this software, and what are their needs and expectations?

- [ ] Can you describe the ideal outcomes or results you envision after implementing this software?

---Shuting Shi---

- [ ]  What are the areas of technical support that we can be provided?

- [ ]  What is your estimated milestone for this project?  (The version 0/ version 1 deadline/ go to production )

- [ ] From this project's privacy perspective, to what degree we can show in our expo, and also should we set our GitHub project to be public?

**Comment by songc120** [comment]
## Summarized questions
- [ ] Is there any existing repo we need to inherit? -> Do we need to make this repo private?
- [ ] What are our users and stakeholders? Will the project only be used by the lab?
- [ ] Who are the primary end-users or beneficiaries of this software, and what are their needs and expectations?
- [ ] Is there any constraint for a programming language(language used in current work), hardware requirements, operating system capability, software version requirements, or framework?
- [ ]  Is there any funding for this project? e.g. AWS usage.
- [ ]  How do we plan our meeting in the following year, and how frequently, and where (virtually or in person)?
- [ ] Who will be added to our project board/project repo as the collaborators/supervisors (I should probably do it)? Would you like to review our documentations?
- [ ] What are the goals or ideal outcomes or results you envision after implementing this software? Or how can we measure it?
- [ ] Compare to an existing product: new features? advantages?
- [ ] Tech support: technology used? expert?
